/* automatically generated by rust-bindgen 0.69.4 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type u8_ = __u8;
pub type __s8 = ::std::os::raw::c_schar;
pub type s8 = __s8;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct retis_probe_offsets {
    pub sk_buff: s8,
    pub skb_drop_reason: s8,
    pub net_device: s8,
    pub net: s8,
    pub nft_pktinfo: s8,
    pub nft_traceinfo: s8,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct retis_probe_config {
    pub offsets: retis_probe_offsets,
    pub stack_trace: u8_,
}
