use std::mem;

use anyhow::Result;

use crate::core::probe::PROBE_MAX;

// Embed in a mod to skip the linter
mod common_uapi {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    // Clippy warns for code generated by bindgen,
    // skip it for this module
    #![allow(clippy::all)]
    include!("./common_uapi.rs");
}

pub(crate) use common_uapi::*;

impl Default for retis_probe_offsets {
    fn default() -> retis_probe_offsets {
        // -1 means the argument isn't available.
        retis_probe_offsets {
            sk_buff: -1,
            skb_drop_reason: -1,
            net_device: -1,
            net: -1,
            nft_pktinfo: -1,
            nft_traceinfo: -1,
        }
    }
}

#[allow(clippy::derivable_impls)]
impl Default for retis_probe_config {
    fn default() -> retis_probe_config {
        retis_probe_config {
            offsets: Default::default(),
            stack_trace: 0,
        }
    }
}

unsafe impl plain::Plain for retis_probe_config {}

// When testing this isn't used as the config map is hidden.
#[cfg_attr(test, allow(dead_code))]
pub(crate) fn init_config_map() -> Result<libbpf_rs::MapHandle> {
    let opts = libbpf_sys::bpf_map_create_opts {
        sz: mem::size_of::<libbpf_sys::bpf_map_create_opts>() as libbpf_sys::size_t,
        ..Default::default()
    };

    Ok(libbpf_rs::MapHandle::create(
        libbpf_rs::MapType::Hash,
        Some("config_map"),
        mem::size_of::<u64>() as u32,
        mem::size_of::<retis_probe_config>() as u32,
        PROBE_MAX as u32,
        &opts,
    )?)
}

#[cfg(not(test))]
pub(crate) fn init_stack_map() -> Result<libbpf_rs::MapHandle> {
    const MAX_STACKTRACE_ENTRIES: u32 = 256;
    const PERF_MAX_STACK_DEPTH: usize = 127;

    let opts = libbpf_sys::bpf_map_create_opts {
        sz: mem::size_of::<libbpf_sys::bpf_map_create_opts>() as libbpf_sys::size_t,
        ..Default::default()
    };

    // Please keep in sync with its BPF counterpart in
    // core/probe/kernel/bpf/include/common.h
    Ok(libbpf_rs::MapHandle::create(
        libbpf_rs::MapType::StackTrace,
        Some("stack_map"),
        mem::size_of::<u32>() as u32,
        (mem::size_of::<u64>() * PERF_MAX_STACK_DEPTH) as u32,
        MAX_STACKTRACE_ENTRIES,
        &opts,
    )?)
}
