/* automatically generated by rust-bindgen 0.70.1 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type u8_ = __u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct retis_global_config {
    pub enabled: u8_,
    pub stack_trace: u8_,
}
pub const LOCAL_STACK_TRACE_ON: enum_LOCAL_STACK_TRACE_ON = 1;
pub type enum_LOCAL_STACK_TRACE_ON = ::std::os::raw::c_uint;
pub const LOCAL_STACK_TRACE_OFF: enum_LOCAL_STACK_TRACE_OFF = 2;
pub type enum_LOCAL_STACK_TRACE_OFF = ::std::os::raw::c_uint;
