/* automatically generated by rust-bindgen 0.72.1 */

pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u64_ = __u64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct log_ratelimit {
    pub last_log_jiffies: u64_,
    pub suppressed: u64_,
}
