/* automatically generated by rust-bindgen 0.71.1 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type __u32 = ::std::os::raw::c_uint;
pub type u8_ = __u8;
pub type u32_ = __u32;
pub const IFNAMSIZ: enum_IFNAMSIZ = 16;
pub type enum_IFNAMSIZ = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct dev_event {
    pub dev_name: [u8_; 16usize],
    pub ifindex: u32_,
    pub iif: u32_,
}
