/* automatically generated by rust-bindgen 0.69.4 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u8_ = __u8;
pub type u32_ = __u32;
pub type u64_ = __u64;
pub const retis_max_comm: ::std::os::raw::c_int = 64;
pub const log_max: ::std::os::raw::c_int = 127;
pub const log_events_max: ::std::os::raw::c_int = 32;
#[doc = " Skip Default trait implementation:\n\n <div rustbindgen nodefault></div>"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct retis_log_event {
    pub level: u8_,
    pub msg: [::std::os::raw::c_char; 127usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct common_event {
    pub timestamp: u64_,
    pub smp_id: u32_,
}
#[doc = " Skip Default trait implementation:\n\n <div rustbindgen nodefault></div>"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct common_task_event {
    pub pid: u64_,
    pub comm: [::std::os::raw::c_char; 64usize],
}
