/* automatically generated by rust-bindgen 0.70.1 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u8_ = __u8;
pub type u32_ = __u32;
pub type u64_ = __u64;
pub type __s32 = ::std::os::raw::c_int;
pub type s32 = __s32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct upcall_enqueue_event {
    pub upcall_ts: u64_,
    pub upcall_cpu: u32_,
    pub queue_id: u32_,
    pub port: u32_,
    pub ret: s32,
    pub cmd: u8_,
}
