/* automatically generated by rust-bindgen 0.70.1 */

pub type __u32 = ::std::os::raw::c_uint;
pub type u32_ = __u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct flow_lookup_ret_event {
    pub ufid: [u32_; 4usize],
    pub n_mask_hit: u32_,
    pub n_cache_hit: u32_,
}
