/* automatically generated by rust-bindgen 0.70.1 */

pub type __u32 = ::std::os::raw::c_uint;
pub type u32_ = __u32;
pub const META: meta_filter_type = 3735928557;
pub type meta_filter_type = ::std::os::raw::c_uint;
pub const META_TARGET_MAX: u32_ = 3735928557;
