/* automatically generated by rust-bindgen 0.71.1 */

pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u64_ = __u64;
pub type __u32 = ::std::os::raw::c_uint;
pub type u32_ = __u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct netns_event {
    pub cookie: u64_,
    pub inum: u32_,
}
