/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct retis_packet_filter_ctx {
    pub data: *mut ::std::os::raw::c_char,
    pub len: ::std::os::raw::c_uint,
    pub ret: ::std::os::raw::c_uint,
}
impl Default for retis_packet_filter_ctx {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FILTER_MAX_INSNS: enum_FILTER_MAX_INSNS = 4096;
pub type enum_FILTER_MAX_INSNS = ::std::os::raw::c_uint;
pub const STACK_RESERVED: enum_STACK_RESERVED = 8;
pub type enum_STACK_RESERVED = ::std::os::raw::c_uint;
pub const SCRATCH_MEM_SIZE: enum_SCRATCH_MEM_SIZE = 4;
pub type enum_SCRATCH_MEM_SIZE = ::std::os::raw::c_uint;
pub const SCRATCH_MEM_START: enum_SCRATCH_MEM_START = 72;
pub type enum_SCRATCH_MEM_START = ::std::os::raw::c_uint;
pub const L2: filter_type = 3735928559;
pub const L3: filter_type = 3735929054;
pub type filter_type = ::std::os::raw::c_uint;
