/* automatically generated by rust-bindgen 0.72.1 */

pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u64_ = __u64;
pub type __u8 = ::std::os::raw::c_uchar;
pub type u8_ = __u8;
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct tracking_config {
    pub free: u8_,
    pub partial_free: u8_,
    pub inv_head: u8_,
    pub no_tracking: u8_,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct tracking_info {
    pub timestamp: u64_,
    pub last_seen: u64_,
    pub orig_head: u64_,
}
