/* automatically generated by rust-bindgen 0.70.1 */

pub type __s32 = ::std::os::raw::c_int;
pub type s32 = __s32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct skb_drop_event {
    pub drop_reason: s32,
}
