/* automatically generated by rust-bindgen 0.71.1 */

pub type __u16 = ::std::os::raw::c_ushort;
pub type __u8 = ::std::os::raw::c_uchar;
pub type u16_ = __u16;
pub type __u32 = ::std::os::raw::c_uint;
pub type u32_ = __u32;
pub type u8_ = __u8;
pub const SECTION_SOCK: sock_sections = 1;
pub const SECTION_RST_REASON: sock_sections = 2;
pub type sock_sections = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct sock_event {
    pub inode: u32_,
    pub type_: u16_,
    pub proto: u16_,
    pub state: u8_,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct sock_rst_reason_event {
    pub reason: u32_,
}
