/* automatically generated by rust-bindgen 0.70.1 */

pub type __u32 = ::std::os::raw::c_uint;
pub type u32_ = __u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct sock_event {
    pub inode: u32_,
}
