/* automatically generated by rust-bindgen 0.72.1 */

pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u64_ = __u64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct skb_tracking_event {
    pub orig_head: u64_,
    pub timestamp: u64_,
    pub skb: u64_,
}
