/* automatically generated by rust-bindgen 0.70.1 */

pub type __u8 = ::std::os::raw::c_uchar;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u8_ = __u8;
pub type u32_ = __u32;
pub type u64_ = __u64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct recv_upcall_event {
    pub key_size: u64_,
    pub batch_ts: u64_,
    pub pkt_size: u32_,
    pub queue_id: u32_,
    pub type_: u32_,
    pub batch_idx: u8_,
}
