[package]
name = "retis-derive"
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[features]
python = []

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version="2.0", features = ["derive"]}
