[package]
name = "retis-pnet"
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
pnet_macros = "0.35"
pnet_macros_support = "0.35"
pnet_packet = "0.35"
