/// # Writer handling file rotation
use std::{
    fs::{self, File, OpenOptions},
    io::{self, BufWriter, Write},
    ops::Drop,
    path::{Path, PathBuf},
};

use anyhow::Result;
use log::error;

use crate::{helpers::time::*, *};

#[derive(Eq, PartialEq)]
pub enum RotationPolicy {
    None,
    Size(usize),
}

/// Writing to a file while following a rotation policy, which if conditions are
/// met can generate multiple files spreading the overall input. A startup event
/// is added at the top of all files generated by the writer.
pub struct RotateWriter {
    inner: BufWriter<File>,
    rotation: RotationPolicy,
    target: PathBuf,
    head: Vec<u8>,
    target_index: usize,
    written: usize,
}

impl RotateWriter {
    /// Create a new RotateWriter given a file path and a rotation policy.
    pub fn new<P: AsRef<Path>>(file: P, rotation: RotationPolicy) -> Result<Self> {
        let mut head = serde_json::to_vec(&startup_event()?)?;
        head.push(b'\n');

        let (inner, written) = Self::new_file(file.as_ref(), &head)?;

        Ok(Self {
            inner,
            rotation,
            target: file.as_ref().to_path_buf(),
            head,
            target_index: 0,
            written,
        })
    }

    fn new_file(target: &Path, head: &[u8]) -> io::Result<(BufWriter<File>, usize)> {
        let mut w = BufWriter::new(
            OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(target)?,
        );

        let written = w.write(head)?;

        Ok((w, written))
    }

    fn close(&mut self) -> io::Result<()> {
        // Flush the current buffer.
        self.flush()?;

        // Move the file, if needed.
        match self.rotation {
            RotationPolicy::None => (),
            RotationPolicy::Size(_) => {
                let mut target = self.target.clone().into_os_string();
                target.push(format!("{}", self.target_index));
                self.target_index += 1;

                fs::rename(&self.target, &target)?;
            }
        }

        Ok(())
    }

    /// Rotate the file.
    fn rotate(&mut self) -> io::Result<()> {
        if self.rotation == RotationPolicy::None {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "Cannot rotate output without a rotation policy",
            ));
        }

        // Close and rename the target file.
        self.close()?;

        // Create the new file.
        (self.inner, self.written) = Self::new_file(&self.target, &self.head)?;

        Ok(())
    }
}

impl Write for RotateWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        match self.rotation {
            RotationPolicy::None => (),
            RotationPolicy::Size(limit) => {
                if self.written + buf.len() > limit {
                    self.rotate()?;
                }
            }
        }

        let written = self.inner.write(buf)?;
        self.written += written;

        Ok(written)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}

impl Drop for RotateWriter {
    fn drop(&mut self) {
        if let Err(e) = self.close() {
            error!("Could not close {}: {e}", self.target.display());
        }
    }
}

/// Generate an event with the startup section. This is used at
/// post-processing time to have insights about the collection environment.
pub(crate) fn startup_event() -> Result<Event> {
    let mut event = Event::new();
    event.common = Some(CommonEvent {
        timestamp: monotonic_timestamp()?,
        ..Default::default()
    });

    event.startup = Some(StartupEvent {
        retis_version: option_env!("RELEASE_VERSION")
            .unwrap_or("unspec")
            .to_string(),
        clock_monotonic_offset: monotonic_clock_offset()?,
    });

    Ok(event)
}
